
arm_controller:
  type: effort_controllers/JointTrajectoryController
  # type: position_controllers/JointGroupPositionController
  # type: position_controllers/JointTrajectoryController
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7

  constraints:
    goal_time: 4.0                   # Override default
    stopped_velocity_tolerance: 0.5 # Override default

  gains:
    # fr3_joint1: { p: 30000, d: 50, i: 0.01 }
    # fr3_joint2: { p: 30000, d: 100, i: 0.01 }
    # fr3_joint3: { p: 30000, d: 50, i: 0.01 }
    # fr3_joint4: { p: 60000, d: 70, i: 0.01 }
    # fr3_joint5: { p: 12000, d: 70, i: 0.01 }
    # fr3_joint6: { p: 7000, d: 50, i: 0.01 }
    # fr3_joint7: { p: 2000, d: 20, i: 0.01 }

    fr3_joint1: { p: 600, d: 30, i: 0.01 }
    fr3_joint2: { p: 600, d: 30, i: 0.01 }
    fr3_joint3: { p: 600, d: 30, i: 0.01 }
    fr3_joint4: { p: 1200, d: 30, i: 0.01 }
    fr3_joint5: { p: 250, d: 10, i: 0.01 }
    fr3_joint6: { p: 150, d: 10, i: 0.01 }
    fr3_joint7: { p: 50, d: 5, i: 0.01 }



hand_controller:
  # type: position_controllers/JointTrajectoryController
  type: effort_controllers/JointTrajectoryController
  joints:
    - fr3_finger_joint1
    - fr3_finger_joint2

  constraints:
    goal_time: 1.2                   # Override default
    stopped_velocity_tolerance: 0.3 # Override default
    
  gains:
    fr3_finger_joint1: { p: 200, d: 0, i: 0.01 }
    fr3_finger_joint2: { p: 200, d: 0, i: 0.01 }

# pid_gains : 
#   robot_back_right_wheel_joint : {p: 100.0, i: 0.01, d: 10.0}
#   robot_front_right_wheel_joint : {p: 100.0, i: 0.01, d: 10.0}
#   robot_back_left_wheel_joint : {p: 100.0, i: 0.01, d: 10.0}
#   robot_back_right_wheel_joint : {p: 100.0, i: 0.01, d: 10.0}